### ISSUE TITLE
Add a custom class globally?

### ISSUE THREAD

**Issue by camskene** [lfridael/ember-cli-font-awesome#22]
Is it possible to add a custom class globally? I would like to give all components a class of .icon but don't want to add {{... classNames="icon"}} to everything.

**Comment by lfridael** [comment]
No, this is not possible. 

Any particular reason why you want to do this? (Personally, I use `i.fa` as the CSS selector.)

**Comment by camskene** [comment]
No big deal, thanks for the work on the integration, it's awesome!
