### ISSUE TITLE
Module cannot be found after install of ember-cli-font-awesome@0.1.0 in ember 1.13.1

### ISSUE THREAD

**Issue by JosephineJ** [lfridael/ember-cli-font-awesome#35]
After installing ember-cli-font-awesome in ember v1.13 according to the readme instructions

````
$ ember install ember-cli-font-awesome
$ ember generate ember-cli-font-awesome
````

routes that contain font-awesome icons will not render. The developer console gives the following error:

````
Uncaught Error: Could not find module `ember-cli-font-awesome/helpers/fa-icon` imported from `my-app/helpers/fa-icon`
````

thrown from /assets/bower_components/loader.js. 

Installing the old version of the addon ember-cli-font-awesome@0.0.9 will fix the issue in my ember installation.

Tested setup:

ember-cli: 1.13.1
ember: 1.13.3
font-awesome: ~4.3.0

built locally with node v0.12.7

**Comment by lfridael** [comment]
@JosephineJ tested this with exactly these library version on OSX, except for Node.js which is still at v0.12.3 and it works for me.

Are you using Windows, OSX or Linux?

**Comment by lfridael** [comment]
1. Upgraded to Node v0.12.7, still works
2. Upgraded to ember-cli v1.13.5, also works

**Comment by JosephineJ** [comment]
@lfridael I am using ember-cli under Ubuntu 14.04. Good to hear, that it is not a node-related issue as you tested it with node v0.12.7. 

Might it be a general dependency-related issue? Something I should check in my dependencies for debugging this? Not really sure where to start

**Comment by JosephineJ** [comment]
Can you post the content of your bower.json and packages.json? I will compare to my setup and try to reproduce if  I find differences in my project

**Comment by lfridael** [comment]
package.json:

```
{
  "name": "issue-35",
  "version": "0.0.0",
  "description": "Small description for issue-35 goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.0.2",
    "ember-cli": "1.13.5",
    "ember-cli-app-version": "0.4.0",
    "ember-cli-babel": "^5.0.0",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "^1.0.0",
    "ember-cli-font-awesome": "0.1.0",
    "ember-cli-htmlbars": "0.7.9",
    "ember-cli-htmlbars-inline-precompile": "^0.1.1",
    "ember-cli-ic-ajax": "0.2.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.3.18",
    "ember-cli-release": "0.2.3",
    "ember-cli-sri": "^1.0.1",
    "ember-cli-uglify": "^1.0.1",
    "ember-data": "1.13.7",
    "ember-disable-proxy-controllers": "^1.0.0",
    "ember-export-application-global": "^1.0.3"
  }
}
```

bower.json

```
{
  "name": "issue-35",
  "dependencies": {
    "ember": "1.13.5",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "ember-cli-test-loader#0.1.3",
    "ember-data": "1.13.7",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.1.5",
    "ember-qunit": "0.4.7",
    "ember-qunit-notifications": "0.0.7",
    "ember-resolver": "~0.1.18",
    "jquery": "^1.11.1",
    "loader.js": "ember-cli/loader.js#3.2.0",
    "qunit": "~1.17.1",
    "font-awesome": "~4.3.0"
  }
}
```

**Comment by JosephineJ** [comment]
@lfridael Thanks for sharing your setup. Couldn't make it work with a similar setup in my old app, so I retried in a fresh Ember app with ember-cli 1.13.1. Here installation of ember-cil-font-awesome@0.1.0 works completely fine! 

Installing the package ember-cli-bootstrap-sass subsequently will reproduce my error that I had before:
````
Uncaught Error: Could not find module `ember-cli-font-awesome/helpers/fa-icon` imported from `portfolio/helpers/fa-icon`
````

Also the following error, of which I didn't know before what it was related to, shows up:

````
Uncaught Error: Cannot call `compile` without the template compiler loaded. Please load `ember-template-compiler.js` prior to calling `compile`.
````

So it seems it's rather an issue with the bootstrap-addon - closing this issue then as installation of font-awesome works fine for me otherwise.

**Comment by lfridael** [comment]
@JosephineJ Thanks for the feedback
